from jinja2 import Template
from .models import ReportPayload

EMAIL_HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<body style="font-family: Arial, sans-serif; color: #333; line-height: 1.6;">
    <h2 style="color: #2c3e50;">Weekly Review Pulse: {{ payload.product }}</h2>
    <p>Hi Team,</p>
    <p>Here are the top insights for <strong>{{ payload.iso_week }}</strong> based on <strong>{{ payload.reviews_analysed }}</strong> reviews (Avg ⭐ {{ "%.1f"|format(payload.avg_rating) }}).</p>
    
    <div style="background-color: #f9f9f9; padding: 15px; border-left: 5px solid #3498db; margin: 20px 0;">
        <h3 style="margin-top: 0;">Top Themes:</h3>
        <ul>
        {% for theme in payload.themes %}
            <li><strong>{{ theme.theme_name }}</strong> ({{ theme.review_count }} reviews)</li>
        {% endfor %}
        </ul>
    </div>

    <p>Detailed analysis, including verbatim quotes and actionable engineering ideas, has been appended to the central product document.</p>
    
    <div style="margin: 30px 0;">
        <a href="{{ payload.doc_url }}#{{ payload.heading_anchor }}" 
           style="background-color: #3498db; color: white; padding: 12px 25px; text-decoration: none; border-radius: 5px; font-weight: bold;">
           View Full Report in Google Docs
        </a>
    </div>

    <p style="font-size: 0.9em; color: #7f8c8d;">
        This report was automatically generated by the Weekly Product Review Pulse AI Agent.<br>
        PII has been redacted from all review text.
    </p>
</body>
</html>
"""

def render_email_html(payload: ReportPayload) -> str:
    """
    Render the report as an HTML email.
    """
    template = Template(EMAIL_HTML_TEMPLATE)
    # Ensure doc_url and anchor are not None for the link
    doc_url = payload.doc_url if payload.doc_url else "#"
    heading_anchor = payload.heading_anchor if payload.heading_anchor else ""
    
    return template.render(payload=payload)
